import Head from "next/head";
import styles from "@/styles/Home.module.css";
import AcAutocomplete from "@/components/autocomplete";
import { AcAutoComplateItem } from "@/components/autocomplete/types";
import { Card, CardContent, CardHeader, Container, Typography } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Card sx={{ width: 300 }}>
            <CardContent>
              <Typography variant="h5">Rick and Morty</Typography>
              <AcAutocomplete options={top100Films} />
            </CardContent>
          </Card>
        </Container>
      </main>
    </>
  );
}

const top100Films: AcAutoComplateItem[] = [
  { label: "The Shawshank Redemption", value: "1994" },
  { label: "The Godfather", value: "1972" },
  { label: "The Godfather: Part II", value: "1974" },
  { label: "The Dark Knight", value: "2008" },
  { label: "12 Angry Men", value: "1957" },
  { label: "Schindler's List", value: "1993" },
  { label: "Pulp Fiction", value: "1994" },
];
